# This file may not be shared/redistributed without permission. Please read copyright notice in the git repo. If this file contains other copyright notices disregard this text.
"""
This project resembles the Inventory-control problem discussed in (Her25, Subsection 5.1.2) but with more complicated rules.
If you are stuck, the inventory-control problem will be a good place to start.

I recommend to use the DP_stochastic function (as we did with the inventory-control example). This means
your main problem is to build appropriate DPModel-classes to represent the different problems.

References:
  [Her25] Tue Herlau. Sequential decision making. (Freely available online), 2025.
"""
from irlc.ex02.dp_model import DPModel
from irlc.ex02.dp import DP_stochastic
import matplotlib.pyplot as plt
from scipy.stats import binom
from irlc import savepdf
import numpy as np

def plot_policy(pi, title, pdf):
    """Helper function to plot the policy functions pi, as generated by the DP_stochastic function. This function
    can be used to visualize which actions are taken in which state (y-axis) at which time step (x-axis)."""
    N = len(pi)
    W = max(pi[0].keys())
    A = np.zeros((W, N))
    for i in range(W):
        for j in range(N):
            A[i, j] = pi[j][i]
    plt.imshow(A)
    plt.title(title)
    savepdf(pdf)
    plt.show()

N_DAYS = 14   # planning horizon
ns = 20   # max storage
no = 15   # max order
co = 1.5  # ordering cost per blaster
sp = 2.1  # sale price per blaster
c_disp = 3.0  # disposal cost per excess blaster (kiosk 2 only)

# Kiosk-1 discrete demand distribution
DEMAND_1 = {0: 0.3, 3: 0.6, 6: 0.1}


class KioskModel1(DPModel):
    """
    State  x in {0,...,ns}  — inventory at start of day
    Action u in {0,...,no}  — blasters ordered
    Noise  w in {0, 3, 6}   — customer demand (Tusken-raider distribution)

    Transition:  x' = min(ns, x + u - w)   [clipped to [0, ns]]
    Stage cost:  g  = co*u - sp*min(x+u, w)
    Terminal:    gN = 0
    """
    def __init__(self):
        super().__init__(N=N_DAYS)

    def S(self, k):
        return range(ns + 1)

    def A(self, x, k):
        return range(no + 1)

    def f(self, x, u, w, k):
        return min(ns, max(0, x + u - w))

    def g(self, x, u, w, k):
        return co * u - sp * min(x + u, w)

    def gN(self, x):
        return 0.0

    def Pw(self, x, u, k):
        return DEMAND_1


# ── Kiosk 2 ───────────────────────────────────────────────────────────────────
class KioskModel2(DPModel):
    """
    Extends KioskModel1 with:
      - Demand ~ Binomial(ns, p=1/5)
      - Disposal cost 3 credits/blaster for any inventory exceeding ns at end of day
    """
    def __init__(self):
        super().__init__(N=N_DAYS)
        # Cache binomial demand distribution once at construction
        self._demand = {
            w: float(binom.pmf(w, ns, 1/5))
            for w in range(ns + 1)
            if binom.pmf(w, ns, 1/5) > 1e-12
        }

    def S(self, k):
        return range(ns + 1)

    def A(self, x, k):
        return range(no + 1)

    def f(self, x, u, w, k):
        return min(ns, max(0, x + u - w))

    def g(self, x, u, w, k):
        sold          = min(x + u, w)
        excess        = max(0, (x + u - sold) - ns)   # blasters above storage limit
        return co * u - sp * sold + c_disp * excess

    def gN(self, x):
        return 0.0

    def Pw(self, x, u, k):
        return self._demand

# ── Warmup (Problems 2) ───────────────────────────────────────────────────────
def warmup_states():
    return set(range(ns + 1))          # S_0 = {0, 1, ..., 20}

def warmup_actions():
    return set(range(no + 1))          # A(x) = {0, 1, ..., 15}


# ── Solvers (Problems 4 & 5) ──────────────────────────────────────────────────
def solve_kiosk_1():
    return DP_stochastic(KioskModel1())

def solve_kiosk_2():
    return DP_stochastic(KioskModel2())


def main():
    # Problem 14
    print("Available states S_0:", warmup_states())
    print("Available actions A_0(x_0):", warmup_actions())

    J, pi = solve_kiosk_1() # Problem 16
    print("Kiosk1: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk1", "Latex/figures/kiosk1")
    plt.show()

    J, pi = solve_kiosk_2() # Problem 17
    print("Kiosk 2: Expected profits: ", -J[0][0], " imperial credits")
    plot_policy(pi, "Kiosk2", "Latex/figures/kiosk2")
    plt.show()


if __name__ == "__main__":
    main()